server:
  port: 8765
  servlet:
    context-path: /square-demo
square:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: admin
    password: 123456
